server:
  port: 8888

spring:
  application:
    name: "shinano-broker"

shinano:
  mq:
    broker:
      port: 10022
      producer-commit-ack-type: async
      producer-commit-ack-batch-size: 100
      producer-commit-ack-ttl: 300
      producer-commit-ack-thread: 3

