server:
  port: 8889

spring:
  application:
    name: "shinano-broker"

shinano:
  mq:
    broker:
      nameserver:
        - localhost:10001
        - localhost:10002
        - localhost:10003
      serviceId: shinano-mq-broker
      type: slave
      address: localhost
      clientId: broker-2
      port: 10023

      producer-commit-ack-type: async
      producer-commit-ack-batch-size: 100
      producer-commit-ack-ttl: 300
      producer-commit-ack-thread: 3
      asyncSendEnable: true

      mappedFileFlushInterval: 10000