shinano:
  mq:
    consumer:
      nameserver:
        - localhost:10001
        - localhost:10002
        - localhost:10003
      serviceId: shinano-mq-consumer
      clientId: consumer-1
      broker-address: 127.0.0.1
      broker-port: 10022
